# NumPy

In [2]:
import numpy as np

## NumPy arrays

In [7]:
a = np.zeros(3)
print(a)
print(type(a))

b = np.array([1, 2, 3])
print(b)
print(type(b))

[0. 0. 0.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


A numpy array may only contain homogeneous (i.e. all elements are of the same type) data from any of the dtypes it provides; the most important data types are float64, int64 and bool.

In [11]:
# The following array is not homogeneous, so it implicitly typecasts True to 1
c = np.array([True, 2, 3])
print(c)

c_1 = np.array([True, False, True])
print(c_1)

[1 2 3]
[ True False  True]


In [13]:
# We can explicitly determine the dtype employed. Notice that float64 is the default type.
d = np.zeros(3)
print(type(d[0]))

d_1 = np.zeros(3, dtype = int)
print(type(d_1[0]))

<class 'numpy.float64'>
<class 'numpy.int32'>


### Shape and dimension

In [18]:
z = np.zeros(10)
print(z.shape)        # z has no dimensions

z.shape = (10, 1)     # z is reshaped to a single dimensioned array
print(z.shape)
print(z)

z.shape = (5, 2)     # z is reshaped to bidimensional, 5x2 array
print(z.shape)
print(z)

(10,)
(10, 1)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
(5, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Creating arrays

In [28]:
emptyArray = np.empty(3)
print(f'emptyArray:\n{emptyArray}')

linearSpace = np.linspace(2, 4, 5)
print(f'\nlinear space from 2 to 4, with 5 elements:\n{linearSpace}')

identity = np.identity(2)
print(f'\n2x2 identity matrix:\n{identity}')

list1 = [1, 2]
list2 = [3, 4]
nparrayFromList = np.array([list1, list2], dtype=float)
print(f'\ncreating an nparray from native Python lists:\n{nparrayFromList}')

emptyArray:
[0. 0. 0.]

linear space from 2 to 4, with 5 elements:
[2.  2.5 3.  3.5 4. ]

2x2 identity matrix:
[[1. 0.]
 [0. 1.]]

creating an nparray from native Python lists:
[[1. 2.]
 [3. 4.]]


### Array indexing

In [34]:
print(f'printing 2 elements, starting at element #0:\n{linearSpace[0:2]}')

print('iterating through a matrix')
print(f'\nprinting an entire row: {nparrayFromList[0, :]}')
print(f'\nprinting an entire column: {nparrayFromList[:, 0]}')

printing 2 elements, starting at element #0:
[2.  2.5]
iterating through a matrix

printing an entire row: [1. 2.]

printing an entire column: [1. 3.]


### Array methods

In [49]:
a = np.array((4, 3, 1, 2))

a.sort()
print(f'sorted array: {a}')

print(f'\nthe maximal value of a: {a.max()}')
print(f'the index of the maximal value of a: {a.argmax()}')

print(f'\nsum of all elements: {a.sum()}')
print(f'the cumulative sum of elements: {a.cumsum()}')
print(f'the cumulative product of elements: {a.cumprod()}')

print(f'\nmean of a: {a.mean()}')
print(f'the variance: {a.var()}')
print(f'the standard deviation: {a.std()}')

# Reshapes the array to a 2x2 matrix, then transposes it
a.shape = (2, 2)
print(f'\nthe transposed matrix:\n{a.T}') # a.T is equivalent to a.transpose()

sorted array: [1 2 3 4]

the maximal value of a: 4
the index of the maximal value of a: 3

sum of all elements: 10
the cumulative sum of elements: [ 1  3  6 10]
the cumulative product of elements: [ 1  2  6 24]

mean of a: 2.5
the variance: 1.25
the standard deviation: 1.118033988749895

the transposed matrix:
[[1 3]
 [2 4]]


## Operations on arrays

### Arithmetic operations

In [60]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f'a + b: {a + b}')
print(f'a * b (multiplies element by element): {a * b}')
print(f'adding a scalar: {a + 10}')
print(f'multiplying by a scalar: {a * 10}')

a + b: [ 6  8 10 12]
a * b (multiplies element by element): [ 5 12 21 32]
adding a scalar: [11 12 13 14]
multiplying by a scalar: [10 20 30 40]


### Matrix multiplication

In [64]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(f'the matricial product of a x b: {a @ b}')

a.shape = (2, 2)
b.shape = (2, 2)
print(f'the matricial product of a x b (a, b have been reshaped to matrixes):\n{a @ b}')

the matricial product of a x b: 70
the matricial product of a x b (a, b have been reshaped to matrixes):
[[19 22]
 [43 50]]


### Mutability and copying arrays

In [67]:
a = np.array([42, 44, 22])
print(a)

a[-1] = 5
print(a)

[42 44 22]
[42 44  5]


In [68]:
a = np.random.randn(3)
print(a)

b = a
b[-1] = 3

print(f'b: {b}')
print(f'a: {a}')

# b mutates a, as 'b = a' causes b to point to the same memory region as a.

[ 1.62947807  2.15844191 -0.91758688]
b: [1.62947807 2.15844191 3.        ]
a: [1.62947807 2.15844191 3.        ]


In [70]:
a = np.random.randn(3)
print(a)

b = np.copy(a)
b[-1] = 3

print(f'b: {b}')
print(f'a: {a}')

# np.copy(a) creates a copy of the original array, making a and b independent from one another
# any changes made to b will only be applied to b

[-0.02115381 -0.36456222  1.60361544]
b: [-0.02115381 -0.36456222  3.        ]
a: [-0.02115381 -0.36456222  1.60361544]


## Additional functionality

### Vectorized functions

In [84]:
%%time
z = np.random.randn(1000000)

print('applying sine to the entire array ...')
z = np.sin(z)

applying sine to the entire array ...
Wall time: 45 ms


In [86]:
%%time
n = len(z)
y = np.empty(n)

print('applying sine to the entire array ...')
for i in range(n):
    y[i] = np.sin(z[i])

applying sine to the entire array ...
Wall time: 1.4 s


In [92]:
x = np.random.randn(4)
print(x)

x_1 = np.where(x > 0, 1, 0)
print(x_1)

[-1.00380191  0.27360037  0.93122245  2.14523155]
[0 1 1 1]


In [94]:
def myFunction(x):
    return 1 if x > 0 else 0

try:
    myFunction(x)
except(ValueError):
    print('given function cannot be vectorized')

given function cannot be vectorized


In [95]:
# Vectorizing a function
newFunction = np.vectorize(myFunction)

x_1 = newFunction(x)
print(x_1)

[0 1 1 1]


### Comparisons

In [101]:
a = np.array([2, 3])
b = np.array([2, 3])

In [105]:
print(a == b)

a[0] = 1
print(a == b)
print(a != b)

[False  True]
[False  True]
[ True False]


In [110]:
z = np.linspace(0, 10, 5)

print(z)
print(z[z > 3])

b = z > 3
print(b)

[ 0.   2.5  5.   7.5 10. ]
[ 5.   7.5 10. ]
[False False  True  True  True]


### Subpackages

In [111]:
z = np.random.randn(10000)  # Generate standard normals
y = np.random.binomial(10, 0.5, size=1000)    # 1,000 draws from Bin(10, 0.5)
y.mean()

5.061

In [112]:
A = np.array([[1, 2], [3, 4]])

np.linalg.det(A)           # Compute the determinant

-2.0000000000000004

In [113]:
np.linalg.inv(A)           # Compute the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])